drop table MARKET_SECTOR if exists;
create table MARKET_SECTOR(
SECTOR_ID bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
SECTOR_NAME varchar NOT NULL UNIQUE, 
SECTOR_DESC varchar);

drop table SECURITIES if exists;
create table SECURITIES(
SYMBOL varchar NOT NULL PRIMARY KEY,
COMPANY_NAME varchar NOT NULL, 
COMPANY_DESC varchar,
SECTOR_ID bigint(20) NOT NULL);

ALTER TABLE SECURITIES
ADD FOREIGN KEY (SECTOR_ID) 
REFERENCES MARKET_SECTOR(SECTOR_ID);

drop table TRADERS if exists;
create table TRADERS(
TRADER_ID bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
FIRST_NAME varchar NOT NULL,
LAST_NAME varchar NOT NULL,
PHONE_NUM bigint(20) NOT NULL,
EMAIL varchar NOT NULL,
ADDRESS varchar NOT NULL,
COMPANY_NAME varchar);

drop table ORDERS if exists;
create table ORDERS(
TRADER_ID bigint(20) NOT NULL,
ORDER_ID bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
SYMBOL varchar NOT NULL,
SIDE varchar NOT NULL,
ORDER_TYPE varchar NOT NULL,
PRICE double NOT NULL,
SHARES bigint(20) NOT NULL,
LAST_UPDATE varchar NOT NULL);

ALTER TABLE ORDERS
ADD FOREIGN KEY (TRADER_ID) 
REFERENCES TRADERS(TRADER_ID);

drop table ORDERTRANS if exists;
create table ORDERTRANS(
TRANS_ID bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
TRANS_ORDER_ID bigint(20) NOT NULL, 
TRANS_CREATION_DATE varchar NOT NULL,
TRANS_ORDER_STATUS varchar NOT NULL,
TRANS_LAST_UPDATE varchar NOT NULL);

ALTER TABLE ORDERTRANS
ADD FOREIGN KEY (TRANS_ORDER_ID) 
REFERENCES ORDERS(ORDER_ID);
