drop table MARKET_SECTOR if exists;
create table MARKET_SECTOR(
SECTOR_ID bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
SECTOR_NAME varchar NOT NULL UNIQUE, 
SECTOR_DESC varchar);

drop table SECURITIES if exists;
create table SECURITIES(
SYMBOL varchar NOT NULL PRIMARY KEY,
COMPANY_NAME varchar NOT NULL, 
COMPANY_DESC varchar,
SECTOR_ID bigint(20) NOT NULL);

ALTER TABLE SECURITIES
ADD FOREIGN KEY (SECTOR_ID) 
REFERENCES MARKET_SECTOR(SECTOR_ID)
